name: Kynema-Driver-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{github.ref}}-${{github.head_ref}}-ci
  cancel-in-progress: true

jobs:
  Formatting:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: 'kynema_driver.cpp ./src'
        exclude: '.'
        extensions: 'H,h,cpp'
        clangFormatVersion: 20
  CPU:
    needs: Formatting
    runs-on: ubuntu-24.04
    container:
      image: roodj/kynema-snapshot:latest
      env:
          KYNEMA_MANAGER: /kynema-manager
          E4S_MACHINE: true
    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Test
        run: |
          /bin/bash -c " \
            source ${KYNEMA_MANAGER}/start.sh && spack-start && \
            spack env activate e4s-build && \
            cd ${KYNEMA_MANAGER}/environments/e4s-build && \
            ln -s ${GITHUB_WORKSPACE} kynema-driver && \
            spack develop --no-modify-concrete-specs --no-clone kynema-driver@main && \
            spack rm kynema && \
            spack add kynema-driver@main~kynema-fmb~kynema_sgf_gpu~kynema_ugf_gpu~tests && \
            spack concretize --reuse -f && \
            spack install && \
            spack cd -b kynema-driver && \
            spack build-env kynema-driver ctest -j $(nproc) -LE no-ci --output-on-failure \
          "
